name: Nightly Restore Gut

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-restore-gut
      device: desktop
      tags: '@restore_gut'
      environment: staging
      report_scope: nightly
    secrets: inherit
