name: Nightly IS Evergreen

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-is-evergreen
      device: desktop
      tags: '@is_evergreen'
      environment: staging
      report_scope: nightly
    secrets: inherit
