name: Nightly TF Evergreen

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-tf-evergreen
      device: desktop
      tags: '@tf_evergreen'
      environment: staging
      report_scope: nightly
    secrets: inherit
