name: Nightly LG Evergreen

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-lg-evergreen
      device: desktop
      tags: '@ageless_evergreen'
      environment: staging
      report_scope: nightly
    secrets: inherit
