name: Nightly Restore Detox

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-restore-detox
      device: desktop
      tags: '@restore_detox'
      environment: staging
      report_scope: nightly
    secrets: inherit
